steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud composer environments storage dags import \
          --environment=${_COMPOSER_ENVIRONMENT} \
          --location=${_COMPOSER_LOCATION} \
          --source=./scripts/DAGs \
          --destination=dags \
