steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud composer environments storage dags import \
          --environment=${_COMPOSER_ENVIRONMENT} \
          --location=${_COMPOSER_LOCATION} \
          --source=./scripts/DAGs \
          --destination=dags
    id: IMPORT

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m rsync -d -r -x ".*\/.*" ./scripts/DAGs gs://${_COMPOSER_BUCKET}/dags/dags/DAGs
    id: DELETION
